mm: damon: Fix compiling on v4.14
../mm/damon/reclaim.c:11:10: fatal error: 'linux/kstrtox.h' file not found
#include <linux/kstrtox.h>
         ^~~~~~~~~~~~~~~~~

../mm/damon/lru_sort.c:11:10: fatal error: 'linux/kstrtox.h' file not found
#include <linux/kstrtox.h>
         ^~~~~~~~~~~~~~~~~

In v4.14, `kstrtobool` is defined in `include/linux/kernel.h`, so there is
no need to import the header file.