(for-v5.4.y) Fix implicit get_task_struct() declaration errors
Commit 0f91d13366a4 ("mm/damon: simplify stop mechanism") causes the
below build error on some systems when applied on damon/for-v5.4.y.

    linux/mm/damon/core.c: In function ‘__damon_stop’:
    linux/mm/damon/core.c:504:3: error: implicit declaration of function ‘get_task_struct’; did you mean ‘set_task_cpu’? [-Werror=implicit-function-declaration]
       get_task_struct(tsk);
       ^~~~~~~~~~~~~~~
       set_task_cpu
    linux/mm/damon/core.c:507:3: error: implicit declaration of function ‘put_task_struct’; did you mean ‘init_srcu_struct’? [-Werror=implicit-function-declaration]
       put_task_struct(tsk);
       ^~~~~~~~~~~~~~~
       init_srcu_struct
    cc1: some warnings being treated as errors

This commit fixes the issue by including the needed header file.

Signed-off-by: SeongJae Park <sj@kernel.org>